// web/src/components/UserMenu.jsx
import React from 'react';
import { AutoAvatar } from 'open-avatar/react';
import { Languages, LogOut, Monitor, Moon, Sun, UserRound } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { Button, Dropdown, Segmented, Space, Typography } from 'antd';

export function UserMenu({ user, themeMode, language, onThemeChange, onLanguageChange, onLogout, profileHref = '/portal/profile' }) {
  const { t } = useTranslation();
  const name = user?.display_name || user?.username || 'IdBridge';

  const themeItems = [
    { value: 'light', label: <Sun size={15} aria-label={t('layout.lightTheme')} /> },
    { value: 'dark', label: <Moon size={15} aria-label={t('layout.darkTheme')} /> },
    { value: 'system', label: <Monitor size={15} aria-label={t('layout.systemTheme')} /> },
  ];
  const languageItems = [
    { value: 'zh-CN', label: <span className="user-segment-label"><Languages size={14} />中</span> },
    { value: 'en-US', label: <span className="user-segment-label"><Languages size={14} />EN</span> },
  ];
  const menuItems = [
    {
      key: 'identity',
      disabled: true,
      label: (
        <Space size={10} className="user-menu-identity">
          <AutoAvatar userIdOrName={name} avatar={user?.avatar_url || ''} shape="circle" size={34} />
          <span>
            <Typography.Text strong>{name}</Typography.Text>
            <Typography.Text type="secondary" className="block-text">{user?.username || user?.email || ''}</Typography.Text>
          </span>
        </Space>
      ),
    },
    { type: 'divider' },
    {
      key: 'preferences',
      label: (
        <div className="user-menu-control-row" onClick={(event) => event.stopPropagation()}>
          <Segmented size="small" value={themeMode} options={themeItems} onChange={onThemeChange} aria-label={t('layout.theme')} />
          <Segmented size="small" value={language} options={languageItems} onChange={onLanguageChange} aria-label={t('layout.language')} />
        </div>
      ),
    },
    { type: 'divider' },
    {
      key: 'profile',
      icon: <UserRound size={15} />,
      label: <a href={profileHref}>{t('layout.profile')}</a>,
    },
    {
      key: 'logout',
      danger: true,
      icon: <LogOut size={15} />,
      label: t('layout.logout'),
      onClick: onLogout,
    },
  ];

  return (
    <Dropdown trigger={['click']} placement="bottomRight" arrow menu={{ items: menuItems }}>
      <Button type="text" className="avatar-trigger" aria-label={t('layout.profile')}>
        <AutoAvatar userIdOrName={name} avatar={user?.avatar_url || ''} shape="circle" size={36} />
      </Button>
    </Dropdown>
  );
}

// web/src/lib/components/layout/UserMenu.svelte
<!-- SPDX-License-Identifier: MIT -->

<script lang="ts">
  import { page } from '$app/stores';
  import type { UserSummary } from '$lib/stores';
  import { getLocale, setTheme, themeMode } from '$lib/stores';
  import { setCurrentLocale, t, type ThemeMode } from '$lib/i18n';
  import { redirectToCurrentPath } from '$lib/session';
  import { AutoAvatar } from 'open-avatar';
  import { KeyRound, LogOut, Moon, Sun, UserRound } from 'lucide-svelte';

  let {
    user = null,
    onlogout,
  }: {
    user: UserSummary | null;
    onlogout: () => void;
  } = $props();

  const displayName = $derived(user?.display_name || user?.username || t('layout.profile'));
  const avatarAlt = $derived(displayName || 'User');
  const isAdmin = $derived($page.url.pathname === '/admin' || $page.url.pathname.startsWith('/admin/'));
  const profileHref = $derived(isAdmin ? '/admin/profile' : '/portal/profile');
  const securityHref = $derived(isAdmin ? '/admin/profile#password' : '/portal/profile#password');
  let currentLocale = $state(getLocale());
  let menuOpen = $state(false);

  const modeOptions = [
    { value: 'light' as ThemeMode, labelKey: 'layout.lightTheme', icon: Sun },
    { value: 'dark' as ThemeMode, labelKey: 'layout.darkTheme', icon: Moon },
  ];

  const avatarSrc = $derived(
    AutoAvatar(user?.id || user?.username || displayName, user?.avatar_url, {
      shape: 'circle',
      size: 64,
      title: avatarAlt,
    }).src,
  );

  const changeThemeMode = (mode: ThemeMode) => {
    setTheme(mode);
  };

  const changeLanguage = (locale: 'en-US' | 'zh-CN') => {
    currentLocale = locale;
    setCurrentLocale(locale);
    redirectToCurrentPath($page.url.pathname, $page.url.search);
  };

  const closeMenu = () => {
    menuOpen = false;
  };

  const handleWindowClick = () => {
    if (menuOpen) closeMenu();
  };
</script>

<svelte:window on:click={handleWindowClick} on:keydown={(event) => event.key === 'Escape' && closeMenu()} />

<div class="relative">
  <button
    class="avatar-menu-trigger"
    type="button"
    aria-label={t('layout.profile')}
    aria-haspopup="menu"
    aria-expanded={menuOpen}
    title={displayName}
    onclick={(event) => {
      event.stopPropagation();
      menuOpen = !menuOpen;
    }}
  >
    <span class="user-avatar">
      <img src={avatarSrc} alt={avatarAlt} />
      <span>{displayName.slice(0, 1).toUpperCase()}</span>
    </span>
  </button>

  {#if menuOpen}
    <div
      class="card absolute right-0 top-full z-50 mt-2 w-72 bg-surface-50-950 border border-surface-200-800 p-2 shadow-xl"
      role="menu"
      tabindex="-1"
      aria-label={t('layout.profile')}
      onclick={(event) => event.stopPropagation()}
      onkeydown={(event) => event.stopPropagation()}
    >
      <div class="border-b border-surface-200-800 pb-3">
        <strong class="block truncate text-sm">{displayName}</strong>
        {#if user}
          <p class="mt-1 truncate text-xs text-surface-600-400">{user.email || user.phone || user.username}</p>
        {/if}
      </div>

      <section class="border-b border-surface-200-800 py-2" aria-label={`${t('layout.theme')} / ${t('layout.language')}`}>
        <div class="compact-pill-row">
          {#each modeOptions as option}
            <button
              class="compact-pill {$themeMode === option.value ? 'active' : ''}"
              type="button"
              onclick={() => changeThemeMode(option.value)}
              aria-pressed={$themeMode === option.value}
              title={t(option.labelKey)}
            >
              <option.icon size={13} aria-hidden="true" />
              <span>{t(option.labelKey)}</span>
            </button>
          {/each}
          <button
            class="compact-pill {currentLocale === 'en-US' ? 'active' : ''}"
            type="button"
            onclick={() => changeLanguage('en-US')}
            aria-pressed={currentLocale === 'en-US'}
          >
            EN
          </button>
          <button
            class="compact-pill {currentLocale === 'zh-CN' ? 'active' : ''}"
            type="button"
            onclick={() => changeLanguage('zh-CN')}
            aria-pressed={currentLocale === 'zh-CN'}
          >
            中
          </button>
        </div>
      </section>

      <div class="py-2">
        <a class="menu-item-link" href={profileHref} role="menuitem">
          <UserRound size={16} aria-hidden="true" />
          <span>{t('layout.profile')}</span>
        </a>
        <a class="menu-item-link" href={securityHref} role="menuitem">
          <KeyRound size={16} aria-hidden="true" />
          <span>{t('profile.changePassword')}</span>
        </a>
      </div>

      <button class="menu-item-link w-full border-t border-surface-200-800 pt-2" type="button" role="menuitem" onclick={onlogout}>
        <LogOut size={16} aria-hidden="true" />
        <span>{t('layout.logout')}</span>
      </button>
    </div>
  {/if}
</div>
